import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import Image from "next/legacy/image";
import devjake from "../public/dev-jake-smile.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
  
    <div className={darkMode ? 'dark' : ""}>
      <Head>
        <title>Jacob Bradshaw Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 selection:bg-yellow-300 selection:text-teal-800'>
        <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-serif dark:text-white'>2023</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/>
              </li>
            <li>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-lg ml-8' href="https://www.linkedin.com/in/jacob-bradshaw-3a31615b/">Resume</a> 
              </li>
          </ul>
        </nav>
        <div className='text-center p-10'>
        <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Jacob Bradshaw</h2>
        <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Developer and Designer</h3>
        <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Freelancer providing services for programming and design content needs. Please look at this site and all my credentials are listed below.
        </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-teal-600'>
          <AiFillTwitterCircle />
          <AiFillLinkedin />
          <AiFillYoutube />
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-400 to-transparent rounded-full w-40 h-60 mt-10 overflow-hidden md:h-90 md:w-106'>
          <Image src={devjake} layout="fill" objectFit='cover'/> 
        </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I Offer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              HTML 5, CSS (Tailwindcss), and Javascript (React). 
              I have worked on various projects 
              including <a href="https://www.valkyriephotos.com/" className='text-teal-500'>Valkyrie Photos</a> website
              for my wife, and an industrial contractor website for a previous student 
              of mine, <span className='text-teal-500'>Kessler Electrical</span>
            </p>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              I have worked as an Industrial Robotics Engineer, Automation Tech Support, Collegiate Curriculum Developer, Associate Professor in Academia, and a Business Owner.
            </p>
          </div>
          <div className='lg:flex gap-5 text-center mx-auto dark:text-white'>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-gray-600'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>
                Example of elegant designs tailored to your specific needs
                </p>
                <h4 className='py-4 text-teal-600 '>Design Tools I Used</h4>
                <p className='text-gray-800 py-1 dark:text-white'>Adobe</p>
                <p className='text-gray-800 py-1 dark:text-white'>Gimp</p>
            </div>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-gray-600'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Wonderful Coding</h3>
              <p className='py-2'>
                Programming IDE that I have used before
                </p>
                <h4 className='py-4 text-teal-600'>Coding Tools I Used</h4>
                <p className='text-gray-800 py-1 dark:text-white'>Visual Studio Code</p>
            </div>
            <div className='text-center shadow-2xl p-10 rounded-xl my-10 dark:bg-gray-600'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Contract Jobs</h3>
              <p className='py-2'>
                Example contract jobs for website creations that are currently in use
                </p>
                <h4 className='py-4 text-teal-600'>Web Developing Tools I Used</h4>
                <p className='text-gray-800 py-1 dark:text-white'>Wix</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800 dark:text-white'>
              HTML 5, CSS (Tailwindcss), and Javascript (React). 
              I have worked on various projects 
              including <a href="https://www.valkyriephotos.com/" className='text-teal-500'>Valkyrie Photos</a> website
              for my wife, and an industrial contractor website for a previous student 
              of mine, <span className='text-teal-500'>Kessler Electrical</span>
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>

            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/> 
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>


          </div>

        </section>
      </main>
    </div>
  );
}
